name = "gamemarket"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[vars]
NODE_VERSION = "20"

[env.production.vars]
NODE_ENV = "production"
NODE_VERSION = "20"
DATABASE_URL = "file:./prisma/prod.db"